version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=dev
      - DB_PASSWORD=dev
      - DB_NAME=battle_versions
      - DEBUG=True
      - LOG_LEVEL=INFO
    volumes:
      - ./config.env:/app/config.env:ro
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway" 